'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { LayoutDashboard, LogIn, LogOut, Menu, ShieldCheck, Users, X } from 'lucide-react';
import { useAuth } from '@/components/auth-provider';

const links = [{ href: '/admin', label: 'Genel bakış', icon: LayoutDashboard }, { href: '/admin/users', label: 'Kullanıcılar', icon: Users }, { href: '/admin/login-history', label: 'Login kayıtları', icon: LogIn }, { href: '/admin/oauth-clients', label: 'OAuth clientleri', icon: ShieldCheck }];

export function AdminShell({ children }: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname(); const { logout, user } = useAuth(); const [open, setOpen] = useState(false); const close = () => setOpen(false);
  return <div className="flex min-h-screen bg-zinc-950 text-zinc-100"><aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-zinc-800 bg-zinc-900 p-5 transition-transform md:static md:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-10 flex items-center justify-between"><Link href="/admin" onClick={close} className="flex items-center gap-3 text-lg font-semibold"><span className="grid size-9 place-items-center rounded-lg bg-zinc-100 text-zinc-900">Z</span>Zyqwax ID</Link><button className="md:hidden" onClick={close} aria-label="Menüyü kapat"><X size={20} /></button></div><p className="mb-3 px-3 text-xs font-semibold tracking-wider text-zinc-500">YÖNETİM</p><nav className="space-y-1">{links.map(({ href, label, icon: Icon }) => { const active = pathname === href; return <Link key={href} href={href} onClick={close} aria-current={active ? 'page' : undefined} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold transition ${active ? 'bg-zinc-700 text-white' : 'text-zinc-400 hover:bg-zinc-800 hover:text-white'}`}><Icon size={20} />{label}</Link>; })}</nav><div className="mt-auto border-t border-zinc-800 pt-4"><p className="truncate px-2 text-sm font-medium text-zinc-200">{user?.name || user?.username || 'Administrator'}</p><p className="truncate px-2 text-xs text-zinc-500">{user?.email}</p><button onClick={() => void logout()} className="mt-3 flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-red-400 hover:bg-zinc-800 hover:text-red-300"><LogOut size={18} />Çıkış yap</button></div></aside>{open && <button className="fixed inset-0 z-30 bg-black/60 md:hidden" onClick={close} aria-label="Menüyü kapat" />}<main className="min-w-0 flex-1"><header className="flex h-20 items-center border-b border-zinc-800 px-5 sm:px-10"><button className="mr-4 rounded-lg p-2 md:hidden" onClick={() => setOpen(true)} aria-label="Menüyü aç"><Menu size={22} /></button><div className="flex items-center gap-3 text-sm text-zinc-500"><span>Admin</span><strong className="text-zinc-700">/</strong><b className="font-medium text-zinc-200">{links.find(link => link.href === pathname)?.label || 'Genel bakış'}</b></div><Link href="/dashboard" className="ml-auto text-sm text-zinc-400 hover:text-white">Kullanıcı paneli</Link></header><div className="mx-auto max-w-7xl p-6 sm:p-10">{children}</div></main></div>;
}
