'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { ApiError, cancelFriendRequest, fetchFriendRequests, respondToFriendRequest, sendFriendRequest, type FriendRequestItem } from '@/lib/api';
import { ListRow } from '@/components/ui/ListRow';
import { Tabs } from '@/components/ui/Tabs';

// Gelen ve gönderilen arkadaşlık isteklerini sekmeler ve aksiyonlarla yönetir.
export default function RequestsPage() {
  const [tab, setTab] = useState<'received' | 'sent'>('received'); const [requests, setRequests] = useState<FriendRequestItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [pending, setPending] = useState<string | null>(null); const [username, setUsername] = useState(''); const [sending, setSending] = useState(false); const [sentMessage, setSentMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRequests((await fetchFriendRequests(tab)).requests); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'İstekler yüklenemedi.'); } finally { setLoading(false); } }, [tab]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function action(id: string, kind: 'accept' | 'decline' | 'cancel') { setPending(id); setError(''); try { if (kind === 'cancel') await cancelFriendRequest(id); else await respondToFriendRequest(id, kind); setRequests((items) => items.filter((item) => item.id !== id)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'İstek güncellenemedi.'); } finally { setPending(null); } }
  async function submit(event: FormEvent) { event.preventDefault(); setSending(true); setError(''); setSentMessage(''); try { await sendFriendRequest(username.trim().toLowerCase()); setUsername(''); setSentMessage('Arkadaşlık isteği gönderildi.'); if (tab === 'sent') void load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'İstek gönderilemedi.'); } finally { setSending(false); } }
  return <div className="dashboard-content"><header className="content-header"><div><p className="section-kicker">SOSYAL / TALEPLER</p><h1>İstekler</h1><p className="content-intro">Yeni bağlantıları gözden geçir.</p></div></header><form className="request-form" onSubmit={submit}><label>Kullanıcı adı<input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="kullanıcı_adı" required /></label><button className="button-primary" disabled={sending}>{sending ? 'Gönderiliyor…' : 'İstek gönder'}</button></form><Tabs tabs={[{ value: 'received', label: 'Gelen' }, { value: 'sent', label: 'Gönderilen' }]} activeValue={tab} onChange={(value) => setTab(value as 'received' | 'sent')} />{sentMessage && <p className="success-message" role="status">{sentMessage}</p>}{loading ? <div className="loading-card">İstekler yükleniyor…</div> : error ? <div className="panel-error" role="alert">{error}<button className="button-secondary mt-4" onClick={() => void load()}>Tekrar dene</button></div> : requests.length === 0 ? <div className="empty-panel">Bu sekmede istek yok.</div> : <div className="list-stack">{requests.map((request) => <ListRow key={request.id} title={request.user.name || request.user.username || 'İsimsiz kullanıcı'} subtitle={request.user.username ? `@${request.user.username}` : undefined} avatarUrl={request.user.avatarUrl} actions={tab === 'received' ? <><button className="button-primary" disabled={pending === request.id} onClick={() => void action(request.id, 'accept')}>Kabul et</button><button className="button-danger" disabled={pending === request.id} onClick={() => void action(request.id, 'decline')}>Reddet</button></> : <button className="button-secondary" disabled={pending === request.id} onClick={() => void action(request.id, 'cancel')}>İptal et</button>} />)}</div>}</div>;
}
